
# Name your project! Project names should contain only lowercase characters and underscores.
name: 'hubspot_tech_assessment'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  hubspot_tech_assessment:
    # Using seeds for an initial ingestion, but disabling on future runs since this is not a long-term ingestion solution
    lianns_fab_rentals:
      +schema: lianns_fab_rentals

models:
  hubspot_tech_assessment:
    staging:
      +materialized: view
      +schema: models
